# Generated by Django 3.2.9 on 2021-11-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPeak',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location_descr', models.CharField(max_length=150, null=True)),
                ('latitude', models.FloatField(default=0, max_length=20)),
                ('longitude', models.FloatField(default=0, max_length=20)),
                ('summit_date', models.DateField(null=True)),
            ],
        ),
    ]
